apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-nvme-block-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10G
  volumeMode: Block
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /dev/nvme0n1p2
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: "kubernetes.io/hostname"    
              operator: In
              values:
                - "velion-worker"
